"""Public Bazel rules for working with GitLab CI configuration.

Today (v0.1.0):

  * `gitlab_ci_validate(name, src)` — build-action rule. Validates
    a `.gitlab-ci.yml` against the official GitLab JSON Schema
    pinned by sha via the `gitlab_schemas` module extension.
    Hermetic; no network, no auth.
  * `gitlab_ci_lint(name, src, host, repo)` — `bazel run`-able
    target. Wraps `glab ci lint <src>` via the `glab` toolchain.
    Hits the GitLab API for full pipeline validation (semantic
    checks beyond pure schema + `include:` resolution). Requires
    `glab auth login` to the target instance.

Future surface:

  * `gitlab_ci_lint_remote(name, src, project)` — call
    `/api/v4/projects/:id/ci/lint` directly (no glab CLI
    indirection), bake the project context.
  * Deploy + registry helpers, schema-derived typed Starlark rules
    for authoring `.gitlab-ci.yml` from Bazel (mirroring the
    rules_jsonschema + rules_cloudformation pattern).

Limitations of `gitlab_ci_validate`:

  * Does not follow `include:` directives. A `.gitlab-ci.yml`
    that imports another project's snippets is validated only at
    its own leaf level; chain validations on the included files
    by registering each as a separate `gitlab_ci_validate`
    target. `gitlab_ci_lint` handles includes server-side.
"""

load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("//gitlab/glab:toolchain_type.bzl", "GLAB_TOOLCHAIN_TYPE")

def _gitlab_ci_validate_impl(ctx):
    stamp = ctx.actions.declare_file(ctx.label.name + ".ok")
    schema = ctx.file._schema
    src = ctx.file.src
    args = ctx.actions.args()
    args.add("--schema", schema.path)
    args.add("--src", src.path)
    args.add("--stamp", stamp.path)
    ctx.actions.run(
        executable = ctx.executable._validator,
        arguments = [args],
        inputs = [schema, src],
        outputs = [stamp],
        mnemonic = "GitlabCiValidate",
        progress_message = "Validating .gitlab-ci.yml against pinned GitLab schema (%s)" % ctx.label,
    )
    return [DefaultInfo(files = depset([stamp]))]

gitlab_ci_validate = rule(
    implementation = _gitlab_ci_validate_impl,
    doc = "Validate a `.gitlab-ci.yml` against the official GitLab JSON Schema (pinned by sha256 via the `gitlab_schemas` module extension). Output: a stamp file Bazel checks for caching; on schema violation the build fails with check-jsonschema's diagnostic on stderr.",
    attrs = {
        "src": attr.label(
            mandatory = True,
            allow_single_file = [".yml", ".yaml"],
            doc = "Label of the `.gitlab-ci.yml` (or sibling fragment) to validate.",
        ),
        "_schema": attr.label(
            default = "@gitlab_ci_schema//file:gitlab-ci.schema.json",
            allow_single_file = True,
        ),
        "_validator": attr.label(
            default = "//gitlab/private:validate",
            executable = True,
            cfg = "exec",
        ),
    },
)

_LINT_TEMPLATE = """#!/usr/bin/env bash
# @generated by gitlab_ci_lint. DO NOT EDIT — re-run \\`bazel build\\` to refresh.
set -euo pipefail

# Locate runfiles. Under `bazel run`, $RUNFILES_DIR is set;
# standalone invocations get `$0.runfiles`.
if [[ -z "${{RUNFILES_DIR:-}}" ]]; then
    if [[ -d "$0.runfiles" ]]; then
        RUNFILES_DIR="$0.runfiles"
    elif [[ -d "${{BASH_SOURCE[0]}}.runfiles" ]]; then
        RUNFILES_DIR="${{BASH_SOURCE[0]}}.runfiles"
    else
        echo "gitlab_ci_lint: cannot locate runfiles directory" >&2
        exit 1
    fi
fi

GLAB_BIN="$RUNFILES_DIR/{glab_runfile}"
SRC="$RUNFILES_DIR/{src_runfile}"

if [[ ! -x "$GLAB_BIN" ]]; then
    echo "gitlab_ci_lint: glab toolchain binary not found at $GLAB_BIN" >&2
    exit 1
fi
if [[ ! -f "$SRC" ]]; then
    echo "gitlab_ci_lint: source not found at $SRC" >&2
    exit 1
fi

# glab uses the current working directory's git remote to choose
# which GitLab instance to talk to. Under `bazel run` the cwd is
# the workspace root, which may or may not be a gitlab repo; pass
# {repo_or_host_args} explicitly to remove the ambiguity.
echo "gitlab_ci_lint: linting $SRC{repo_or_host_log}" >&2

exec "$GLAB_BIN" ci lint{repo_or_host_args} "$SRC" "$@"
"""

def _runfile_path(ctx, f):
    if f.short_path[:3] == "../":
        return f.short_path[3:]
    return ctx.workspace_name + "/" + f.short_path

def _gitlab_ci_lint_impl(ctx):
    glab_info = ctx.toolchains[GLAB_TOOLCHAIN_TYPE].glab_info
    glab_exec = glab_info.glab.executable
    src = ctx.file.src

    # Compose glab flags from the user-set host/repo. Either can be
    # blank — in that case glab falls back to git-remote detection
    # (likely irrelevant in the Bazel sandbox), so we strongly
    # recommend setting at least `repo`.
    repo_arg = ""
    log_suffix = ""
    if ctx.attr.repo:
        repo_arg = " -R " + ctx.attr.repo
        log_suffix = " (repo=" + ctx.attr.repo + ")"
    elif ctx.attr.host:
        # `-R` accepts a full URL; use the host attr to assemble a
        # placeholder url that anchors the gitlab instance even
        # when the project path isn't known.
        repo_arg = " -R https://" + ctx.attr.host
        log_suffix = " (host=" + ctx.attr.host + ")"

    launcher = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(
        launcher,
        _LINT_TEMPLATE.format(
            glab_runfile = _runfile_path(ctx, glab_exec),
            src_runfile = _runfile_path(ctx, src),
            repo_or_host_args = repo_arg,
            repo_or_host_log = log_suffix,
        ),
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = [src, glab_exec]).merge(
        glab_info.default_runfiles,
    )
    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

gitlab_ci_lint = rule(
    implementation = _gitlab_ci_lint_impl,
    executable = True,
    doc = "`bazel run`-able target that lints a `.gitlab-ci.yml` via `glab ci lint`. Network-bound: hits the GitLab API, requires the user to be `glab auth login`-ed to the target instance. For hermetic schema-only validation, use `gitlab_ci_validate` instead.",
    attrs = {
        "src": attr.label(
            mandatory = True,
            allow_single_file = [".yml", ".yaml"],
            doc = "Label of the `.gitlab-ci.yml` (or fragment) to lint.",
        ),
        "host": attr.string(
            doc = "GitLab host (e.g. `gitlab.savvifi.com`). " +
                  "Used to anchor `glab`'s API target when the " +
                  "runfiles cwd doesn't have a gitlab remote. " +
                  "Ignored if `repo` is set (which carries host).",
        ),
        "repo": attr.string(
            doc = "`OWNER/REPO` or full URL passed as `glab -R`. " +
                  "Strongly recommended — lets `glab` pick the right " +
                  "GitLab instance + project context without inspecting " +
                  "the sandbox's git state.",
        ),
    },
    toolchains = [GLAB_TOOLCHAIN_TYPE],
)

# ─── gitlab_ci: generate a .gitlab-ci.yml from a typed Starlark spec ──
#
# The Starlark side assembles the spec in a fixed canonical key order
# and `json.encode`s it; the `//gitlab/private:emit` ruamel.yaml binary
# dumps it deterministically to `.gitlab-ci.yml` (reviving `!reference`
# tags). The macro then chains `gitlab_ci_validate` (build-time schema
# gate) and aspect_bazel_lib `write_source_files` (`<name>.update`:
# `bazel run` writes the file back into the tree, `bazel test` checks it
# is current). Same generate→write_source_files shape as rules_vscode.

def _gitlab_ci_impl(ctx):
    out = ctx.actions.declare_file(ctx.attr.out)
    spec = ctx.actions.declare_file(ctx.label.name + ".spec.json")
    ctx.actions.write(spec, ctx.attr.spec_json)
    args = ctx.actions.args()
    args.add("--spec", spec.path)
    args.add("--out", out.path)
    ctx.actions.run(
        executable = ctx.executable._emitter,
        arguments = [args],
        inputs = [spec],
        outputs = [out],
        mnemonic = "GitlabCiEmit",
        progress_message = "Emitting .gitlab-ci.yml (%s)" % ctx.label,
    )
    return [DefaultInfo(files = depset([out]))]

_gitlab_ci = rule(
    implementation = _gitlab_ci_impl,
    doc = "Emit a `.gitlab-ci.yml` from a canonical JSON spec (use the `gitlab_ci` macro, not this rule directly).",
    attrs = {
        "out": attr.string(mandatory = True, doc = "Output filename."),
        "spec_json": attr.string(mandatory = True, doc = "Canonical JSON spec, pre-encoded by the macro."),
        "_emitter": attr.label(
            default = "//gitlab/private:emit",
            executable = True,
            cfg = "exec",
        ),
    },
)

def gitlab_job(
        stage = None,
        script = None,
        image = None,
        services = None,
        before_script = None,
        after_script = None,
        rules = None,
        needs = None,
        artifacts = None,
        variables = None,
        cache = None,
        tags = None,
        environment = None,
        when = None,
        allow_failure = None,
        interruptible = None,
        timeout = None,
        retry = None,
        parallel = None,
        coverage = None,
        extends = None,
        dependencies = None,
        extra = {}):
    """Build one GitLab CI job as a `None`-stripped, key-ordered dict.

    Returns a plain dict (Starlark structs aren't `json.encode`-able), so
    pass the result as a value in `gitlab_ci(jobs = {...})`. Any key not
    modeled here can be supplied via `extra` (a raw dict, merged last).
    """
    modeled = {
        "extends": extends,
        "stage": stage,
        "image": image,
        "services": services,
        "variables": variables,
        "cache": cache,
        "before_script": before_script,
        "script": script,
        "after_script": after_script,
        "artifacts": artifacts,
        "rules": rules,
        "needs": needs,
        "dependencies": dependencies,
        "tags": tags,
        "environment": environment,
        "when": when,
        "allow_failure": allow_failure,
        "interruptible": interruptible,
        "timeout": timeout,
        "retry": retry,
        "parallel": parallel,
        "coverage": coverage,
    }
    # Drop unset fields; the emitter applies the canonical key order, so the
    # dict order here doesn't matter (json.encode sorts it regardless).
    job = {k: v for k, v in modeled.items() if v != None}
    for k, v in extra.items():
        job[k] = v
    return job

def gitlab_reference(*parts):
    """Emit a GitLab `!reference [job, key, ...]` tag value.

    Usable as a value anywhere in a spec; survives `json.encode` as a
    sentinel the emitter turns back into a real `!reference` YAML tag.
    """
    return {"__gitlab_reference__": list(parts)}

def gitlab_ci(
        name,
        stages = [],
        variables = {},
        default = None,
        image = None,
        include = None,
        workflow = None,
        jobs = {},
        extra = {},
        out = None,
        write_to = None,
        validate = True,
        **kwargs):
    """Generate a `.gitlab-ci.yml` from a typed Starlark spec.

    Assembles the spec in a fixed top-level order (include, workflow,
    default, image, stages, variables, jobs sorted by name, extra),
    emits it deterministically as YAML, and (by default) schema-validates
    the result. Set `write_to` (e.g. `".gitlab-ci.yml"`) to also create
    `<name>.update` — `bazel run …:<name>.update` writes the file into the
    source tree; `bazel test …:<name>.update` checks it is up to date.

    Args:
      name: target name.
      stages: list of stage names (order preserved).
      variables: global CI variables (dict).
      default: the `default:` job-config block (dict).
      image: top-level default image (str or dict).
      include: `include:` entries (list).
      workflow: the `workflow:` block (dict).
      jobs: dict of job-name -> job (a `gitlab_job(...)` dict or a raw dict).
      extra: escape hatch — raw dict merged at the top level last.
      out: output filename; defaults to `<name>.gitlab-ci.yml`.
      write_to: source-relative path to also create `<name>.update`.
      validate: chain `gitlab_ci_validate` on the generated file (default True).
      **kwargs: forwarded to the underlying rule (visibility, tags, …).
    """
    out = out if out else (name + ".gitlab-ci.yml")

    spec = {}
    if include != None:
        spec["include"] = include
    if workflow != None:
        spec["workflow"] = workflow
    if default != None:
        spec["default"] = default
    if image != None:
        spec["image"] = image
    if stages:
        spec["stages"] = stages
    if variables:
        spec["variables"] = variables
    for job_name in sorted(jobs.keys()):
        spec[job_name] = jobs[job_name]
    for k, v in extra.items():
        spec[k] = v

    _gitlab_ci(
        name = name,
        out = out,
        spec_json = json.encode(spec),
        **kwargs
    )
    if validate:
        gitlab_ci_validate(
            name = name + "_validate",
            src = ":" + name,
            **{k: kwargs[k] for k in ["visibility"] if k in kwargs}
        )
    if write_to:
        write_source_files(
            name = name + ".update",
            files = {write_to: ":" + name},
            visibility = kwargs.get("visibility", None),
        )
