"""Entry point for the `gitlab_ci` generation rule.

Reads a canonical JSON spec (assembled in Starlark by the `gitlab_ci`
macro) and emits a deterministic `.gitlab-ci.yml` via ruamel.yaml —
the YAML convention for GitLab CI (block `script:` sequences, no
quote-noise, the `!reference [job, key]` tag).

`!reference` tags can't survive JSON, so the macro encodes them as
`{"__gitlab_reference__": ["job", "key"]}` sentinels; this emitter
turns each back into a real `!reference` YAML tag — symmetric to the
load-side `_absorb_unknown_tag` constructor in validate_main.py, so
the generated file re-parses under the validator (which runs on it as
part of the gate).

Determinism (so write_source_files / diff_test gates stay stable):
key order is preserved from the JSON (the macro fixes it), ruamel
key-sorting stays off, line width is pinned high (no wrap reflow),
indent is fixed, and no `...` document-end marker is emitted.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

_REFERENCE_KEY = "__gitlab_reference__"

# Canonical key order for any map (Starlark's json.encode sorts keys, so the
# emitter is the single source of truth for order). Keys present here are
# emitted in this order; everything else (job names, `extra`/unmodeled keys)
# follows, sorted, for determinism. Covers both top-level and job keys so a
# single pass reads conventionally wherever a key appears.
_KEY_PRIORITY = [
    # top-level structural
    "include",
    "workflow",
    "stages",
    "default",
    # job identity
    "extends",
    "stage",
    # environment / config (top-level and job)
    "image",
    "services",
    "variables",
    "cache",
    # commands
    "before_script",
    "script",
    "after_script",
    # the rest
    "artifacts",
    "rules",
    "needs",
    "dependencies",
    "tags",
    "environment",
    "when",
    "allow_failure",
    "interruptible",
    "timeout",
    "retry",
    "parallel",
    "coverage",
]
_PRIORITY_INDEX = {k: i for i, k in enumerate(_KEY_PRIORITY)}


def _ordered_keys(keys):
    known = [k for k in _KEY_PRIORITY if k in keys]
    rest = sorted(k for k in keys if k not in _PRIORITY_INDEX)
    return known + rest


class _Reference:
    """A GitLab `!reference [job, key, ...]` tag value."""

    def __init__(self, parts):
        self.parts = list(parts)


def _represent_reference(representer, data):  # type: ignore[no-untyped-def]
    # flow_style=True → inline `!reference [job, key]` (GitLab's form).
    return representer.represent_sequence("!reference", data.parts, flow_style=True)


def _convert(value):  # type: ignore[no-untyped-def]
    """Recursively rebuild ruamel's ordered `CommentedMap`/`CommentedSeq`
    from the macro's JSON, applying `_ordered_keys` to every map (so the
    output reads conventionally + deterministically regardless of
    json.encode's key sorting). `{__gitlab_reference__: [...]}` revives into
    a `_Reference` tag object."""
    if isinstance(value, dict):
        if len(value) == 1 and _REFERENCE_KEY in value:
            return _Reference(value[_REFERENCE_KEY])
        m = CommentedMap()
        for k in _ordered_keys(value.keys()):
            m[k] = _convert(value[k])
        return m
    if isinstance(value, list):
        s = CommentedSeq()
        for v in value:
            s.append(_convert(v))
        return s
    return value


def _make_yaml() -> YAML:
    yaml = YAML()  # round-trip dumper: preserves mapping insertion order
    yaml.default_flow_style = False
    yaml.width = 4096  # don't reflow long lines (a classic ruamel diff churn)
    yaml.indent(mapping=2, sequence=4, offset=2)
    yaml.explicit_end = False
    yaml.representer.add_representer(_Reference, _represent_reference)
    return yaml


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args(argv)

    with open(args.spec) as f:
        spec = _convert(json.load(f))

    yaml = _make_yaml()
    with open(args.out, "w") as f:
        f.write(
            "# @generated by rules_gitlab//gitlab:gitlab_ci. DO NOT EDIT —\n"
            "# edit the gitlab_ci(...) target, then `bazel run <pkg>:<name>.update`.\n",
        )
        yaml.dump(spec, f)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
